In [1]:
# Bagged Decision Trees for Classification
from pandas import read_csv
from sklearn.model_selection import KFold
from sklearn.model_selection import cross_val_score
from sklearn.ensemble import BaggingClassifier
from sklearn.tree import DecisionTreeClassifier
filename = 'Fraud_check.csv'
dataframe = read_csv(filename)
array = dataframe.values
X = array[:,0:4]
Y = array[:,4]
seed = 7

In [1]:
import pandas as pd
import matplotlib.pyplot as plt
from sklearn import datasets  
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.tree import  DecisionTreeClassifier
from sklearn import tree
from sklearn.metrics import classification_report
from sklearn import preprocessing

In [2]:
# import some data to play with
Fraud_check = pd.read_csv('C:\\Users\\usr\\Desktop\\New folder\\Fraud_check.csv',index_col=0)

In [4]:
Fraud_check.head()

Marital.Status  Taxable.Income  City.Population  Work.Experience  \
Undergrad                                                                    
NO                Single           68833            50047               10   
YES             Divorced           33700           134075               18   
NO               Married           36925           160205               30   
YES               Single           50190           193264               15   
NO               Married           81002            27533               28   

          Urban  
Undergrad        
NO          YES  
YES         YES  
NO          YES  
YES         YES  
NO           NO

In [7]:
Fraud_check.Urban.unique()

array(['YES', 'NO'], dtype=object)

In [8]:
#Complete dataset
label_encoder = preprocessing.LabelEncoder()
Fraud_check ['Urban']= label_encoder.fit_transform(Fraud_check ['Urban']) 
Fraud_check ['Urban']

Undergrad
NO     1
YES    1
NO     1
YES    1
NO     0
      ..
YES    1
YES    1
NO     1
YES    0
NO     0
Name: Urban, Length: 600, dtype: int32

In [9]:
x=Fraud_check .iloc[:,1:4]
y=Fraud_check ['Urban']

In [10]:
x

Taxable.Income  City.Population  Work.Experience
Undergrad                                                  
NO                  68833            50047               10
YES                 33700           134075               18
NO                  36925           160205               30
YES                 50190           193264               15
NO                  81002            27533               28
...                   ...              ...              ...
YES                 76340            39492                7
YES                 69967            55369                2
NO                  47334           154058                0
YES                 98592           180083               17
NO                  96519           158137               16

[600 rows x 3 columns]

In [11]:
y

Undergrad
NO     1
YES    1
NO     1
YES    1
NO     0
      ..
YES    1
YES    1
NO     1
YES    0
NO     0
Name: Urban, Length: 600, dtype: int32

In [12]:
Fraud_check ['Urban'].unique()

array([1, 0])

In [43]:
colnames = list(Fraud_check .columns)
colnames

['marital', 'population', 'experience', 'urban', 'income']

In [44]:
# Splitting data into training and testing data set
x_train, x_test,y_train,y_test = train_test_split(x,y, test_size=0.2)

In [22]:
model = DecisionTreeClassifier()
model.fit(x_train,y_train)

DecisionTreeClassifier()

In [23]:
#Predicting on test data
preds = model.predict(x_test) # predicting on test data set 
pd.Series(preds).value_counts() # getting the count of each category 

0    61
1    59
dtype: int64

In [24]:
preds

array([1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0,
       0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0,
       1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1,
       1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1,
       1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1,
       1, 1, 0, 1, 0, 1, 1, 1, 0, 0])

In [25]:
y_test

Undergrad
NO     1
YES    1
YES    0
YES    0
YES    0
      ..
NO     0
YES    1
NO     1
YES    1
YES    0
Name: Urban, Length: 120, dtype: int32

In [26]:
pd.crosstab(y_test,preds) # getting the 2 way table to understand the correct and wrong predictions

col_0   0   1
Urban        
0      31  24
1      30  35

In [27]:
# Accuracy 
np.mean(preds==y_test)

0.55

In [28]:
from sklearn.tree import DecisionTreeClassifier
model_gini = DecisionTreeClassifier(criterion='gini', max_depth=3)

In [29]:
model_gini.fit(x_train, y_train)

DecisionTreeClassifier(max_depth=3)

In [30]:
#Prediction and computing the accuracy
pred=model.predict(x_test)
np.mean(preds==y_test)

0.55

In [31]:
array = Fraud_check.values
X = array[:,1:3]
y = array[:,3]

In [34]:
# Decision Tree Regression
from sklearn.tree import DecisionTreeRegressor

In [32]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=1)

In [35]:
model = DecisionTreeRegressor()
model.fit(X_train, y_train)

DecisionTreeRegressor()

In [36]:
#Find the accuracy
model.score(X_test,y_test)

-1.3016925583113284

In [18]:
##Converting the Taxable income variable to bucketing. 
Fraud_check["income"]="<=30000"
Fraud_check.loc[Fraud_check["Taxable.Income"]>=30000,"income"]="Good"
Fraud_check.loc[Fraud_check["Taxable.Income"]<=30000,"income"]="Risky"


In [19]:

##Droping the Taxable income variable
Fraud_check.drop(["Taxable.Income"],axis=1,inplace=True)

In [20]:
Fraud_check.rename(columns={"Undergrad":"undergrad","Marital.Status":"marital","City.Population":"population","Work.Experience":"experience","Urban":"urban"},inplace=True)
## As we are getting error as "ValueError: could not convert string to float: 'YES'".
## Model.fit doesnt not consider String. So, we encode

In [21]:
from sklearn import preprocessing
le=preprocessing.LabelEncoder()
for column_name in Fraud_check.columns:
    if Fraud_check[column_name].dtype == object:
        Fraud_check[column_name] = le.fit_transform(Fraud_check[column_name])
    else:
        pass

In [67]:
##Splitting the data into featuers and labels
features = Fraud_check.iloc[:,0:4]
labels = Fraud_check


In [64]:
## Collecting the column names
colnames = list(Fraud_check.columns)
predictors = colnames[0:4]
target = colnames[4]

In [65]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.2,stratify = y)

In [66]:
##Model building
from sklearn.ensemble import RandomForestClassifier as RF
model = RF(n_jobs = 3,n_estimators = 15, oob_score = True, criterion = "entropy")
model.fit(x_train,y_train)


RandomForestClassifier(criterion='entropy', n_estimators=15, n_jobs=3,
                       oob_score=True)

In [47]:
model.estimators_
model.classes_
model.n_features_
model.n_classes_

2

In [48]:
model.n_outputs_

1

In [49]:
model.oob_score_

1.0

In [50]:
##Predictions on train data
prediction = model.predict(x_train)


In [51]:
prediction

array([1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0,
       0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0,
       0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1,
       1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0,
       1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0,
       1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1,
       1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0,
       1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1,
       0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1,
       1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1,
       1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0,
       0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1,
       1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0,

In [53]:
accuracy

1.0

In [54]:
np.mean(prediction == y_train)

1.0

In [55]:
##Confusion matrix
from sklearn.metrics import confusion_matrix
confusion = confusion_matrix(y_train,prediction)


In [69]:
##Prediction on test data
pred_test = model.predict(x_test)
pred_test

array([0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1,
       1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0,
       0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0,
       1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0,
       1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 0, 0, 0, 1, 1, 1, 0, 0], dtype=int64)

In [57]:
##Accuracy
acc_test =accuracy_score(y_test,pred_test)

In [70]:
acc_test

1.0

In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.metrics import f1_score
from sklearn.model_selection import train_test_split

# Importing dataset
df=pd.read_csv('Fraud_check.csv')
df.head()

Undergrad Marital.Status  Taxable.Income  City.Population  Work.Experience  \
0        NO         Single           68833            50047               10   
1       YES       Divorced           33700           134075               18   
2        NO        Married           36925           160205               30   
3       YES         Single           50190           193264               15   
4        NO        Married           81002            27533               28   

  Urban  
0   YES  
1   YES  
2   YES  
3   YES  
4    NO

In [14]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 42)

In [15]:
print('Shape of x_train=>',x_train.shape)
print('Shape of x_test=>',x_test.shape)
print('Shape of y_train=>',y_train.shape)
print('Shape of y_test=>',y_test.shape)

Shape of x_train=> (480, 3)
Shape of x_test=> (120, 3)
Shape of y_train=> (480,)
Shape of y_test=> (120,)


In [16]:
# Building Decision Tree
from sklearn.tree import DecisionTreeClassifier
dt = DecisionTreeClassifier(criterion = 'entropy', random_state = 42)
dt.fit(x_train, y_train)
dt_pred_train = dt.predict(x_train)

In [19]:
import pandas as pd
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression()
classifier.fit(x_train,y_train)
#Predict for X dataset
y_pred = classifier.predict(x_train)
y_pred

array([0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0,
       0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1,
       1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1,
       0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1,
       1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0,
       0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0,
       1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0,
       1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0,
       1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1,
       0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1,
       0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0,
       1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1,

In [20]:
# Evaluation on Training set
dt_pred_train = dt.predict(x_train)
print('Training Set Evaluation F1-Score=>',f1_score(y_train,dt_pred_train))

Training Set Evaluation F1-Score=> 1.0


In [21]:
# Evaluating on Test set
dt_pred_test = dt.predict(x_test)
print('Testing Set Evaluation F1-Score=>',f1_score(y_test,dt_pred_test))

Testing Set Evaluation F1-Score=> 0.6046511627906976


In [23]:
# Building  Random Forest Classifier
from sklearn.ensemble import RandomForestClassifier
rfc = RandomForestClassifier(criterion = 'entropy', random_state = 42)
rfc.fit(x_train, y_train)

# Evaluating on Training set
rfc_pred_train = rfc.predict(x_train)
print('Training Set Evaluation F1-Score=>',f1_score(y_train,rfc_pred_train))


Training Set Evaluation F1-Score=> 1.0


In [24]:
# Evaluating on Test set
rfc_pred_test = rfc.predict(x_test)
print('Testing Set Evaluation F1-Score=>',f1_score(y_test,rfc_pred_test))

Testing Set Evaluation F1-Score=> 0.6046511627906976
